import './keditor-component-generic';
import './keditor-component-text';
import './keditor-component-photo';
import './keditor-component-image';
import './keditor-component-gallery';
import './keditor-component-youtube-video';
// import './keditor-component-audio';
// import './keditor-component-form';
// import './keditor-component-googlemap';
// import './keditor-component-video';
// import './keditor-component-vimeo';
// import './keditor-component-youtube';