import './keditor-component-generic';
import './keditor-component-audio';
import './keditor-component-form';
import './keditor-component-googlemap';
import './keditor-component-photo';
import './keditor-component-text';
import './keditor-component-video';
import './keditor-component-vimeo';
import './keditor-component-youtube';